CREATE TABLE IF NOT EXISTS "quickbooks"."customers" (
	"id" text PRIMARY KEY NOT NULL,
	"realm_id" text NOT NULL,
	"display_name" text NOT NULL,
	"given_name" text,
	"family_name" text,
	"company_name" text,
	"primary_email_addr" text,
	"mobile_phone" text,
	"primary_phone" text,
	"alternate_phone" text,
	"fax" text,
	"website" text,
	"bill_line1" text,
	"bill_line2" text,
	"bill_city" text,
	"bill_state" text,
	"bill_postal_code" text,
	"bill_country" text,
	"ship_line1" text,
	"ship_line2" text,
	"ship_city" text,
	"ship_state" text,
	"ship_postal_code" text,
	"ship_country" text,
	"taxable" boolean,
	"balance" double precision DEFAULT 0 NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"notes" text,
	"sync_token" text,
	"metadata" json,
	"last_synced" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_updated" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "quickbooks"."estimates_line_items" (
	"id" bigint PRIMARY KEY NOT NULL,
	"estimate_id" text NOT NULL,
	"line_num" integer,
	"detail_type" text,
	"item_ref_id" text,
	"item_ref_name" text,
	"description" text,
	"service_date" date,
	"qty" double precision,
	"unit_price" double precision,
	"amount" double precision,
	"tax_code_ref_id" text,
	"tax_code_ref_name" text,
	"class_ref_id" text,
	"class_ref_name" text,
	"last_synced" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_updated" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "quickbooks"."estimates" (
	"id" text PRIMARY KEY NOT NULL,
	"realm_id" text NOT NULL,
	"doc_number" text,
	"txn_date" date,
	"expiration_date" date,
	"total_amt" double precision DEFAULT 0 NOT NULL,
	"status" text,
	"customer_id" text,
	"customer_ref_name" text,
	"email_status" text,
	"print_status" text,
	"currency_ref" text,
	"exchange_rate" double precision,
	"bill_line1" text,
	"bill_line2" text,
	"bill_city" text,
	"bill_state" text,
	"bill_postal_code" text,
	"bill_country" text,
	"ship_line1" text,
	"ship_line2" text,
	"ship_city" text,
	"ship_state" text,
	"ship_postal_code" text,
	"ship_country" text,
	"private_note" text,
	"memo" text,
	"sync_token" text,
	"metadata_create_time" timestamp with time zone,
	"metadata_last_updated_time" timestamp with time zone,
	"last_synced" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_updated" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "quickbooks"."invoices_line_items" (
	"id" bigint PRIMARY KEY NOT NULL,
	"invoice_id" text NOT NULL,
	"line_num" integer,
	"detail_type" text,
	"item_ref_id" text,
	"item_ref_name" text,
	"description" text,
	"service_date" date,
	"qty" double precision,
	"unit_price" double precision,
	"amount" double precision,
	"tax_code_ref_id" text,
	"tax_code_ref_name" text,
	"class_ref_id" text,
	"class_ref_name" text,
	"last_synced" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_updated" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "quickbooks"."invoices" (
	"id" text PRIMARY KEY NOT NULL,
	"realm_id" text NOT NULL,
	"doc_number" text,
	"txn_date" date,
	"due_date" date,
	"customer_id" text,
	"customer_ref_name" text,
	"total_amt" double precision DEFAULT 0 NOT NULL,
	"balance" double precision DEFAULT 0 NOT NULL,
	"currency_ref" text,
	"exchange_rate" double precision,
	"bill_line1" text,
	"bill_line2" text,
	"bill_city" text,
	"bill_state" text,
	"bill_postal_code" text,
	"bill_country" text,
	"ship_line1" text,
	"ship_line2" text,
	"ship_city" text,
	"ship_state" text,
	"ship_postal_code" text,
	"ship_country" text,
	"email_status" text,
	"print_status" text,
	"private_note" text,
	"memo" text,
	"status" text,
	"sync_token" text,
	"metadata_create_time" timestamp with time zone,
	"metadata_last_updated_time" timestamp with time zone,
	"last_synced" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_updated" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "quickbooks"."items" (
	"id" text PRIMARY KEY NOT NULL,
	"realm_id" text NOT NULL,
	"name" text NOT NULL,
	"sku" text,
	"description" text,
	"type" text,
	"active" boolean DEFAULT true NOT NULL,
	"taxable" boolean,
	"unit_price" double precision,
	"sales_price" double precision,
	"qty_on_hand" double precision,
	"income_account_ref_id" text,
	"expense_account_ref_id" text,
	"asset_account_ref_id" text,
	"sync_token" text,
	"metadata" json,
	"last_synced" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_updated" timestamp with time zone DEFAULT now() NOT NULL,
	"track_qty_on_hand" boolean,
	"inv_start_date" date
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "quickbooks"."tokens" (
	"id" bigint PRIMARY KEY NOT NULL,
	"realm_id" text NOT NULL,
	"access_token" text NOT NULL,
	"refresh_token" text NOT NULL,
	"token_type" text,
	"scope" text,
	"expires_at" timestamp with time zone,
	"refresh_token_expires_at" timestamp with time zone,
	"environment" text,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_updated" timestamp with time zone DEFAULT now() NOT NULL
);
