name: Deploy to Production Server

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        cd backend
        npm ci
        
    - name: Build backend
      run: |
        cd backend
        npm run build
        
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        script: |
          # Navigate to project directory
          cd /home/${{ secrets.SERVER_USER }}/dash3
          
          # Pull latest changes
          git pull origin master
          
          # Install/update dependencies
          cd backend
          npm ci --production
          
          # Build the application
          npm run build
          
          # Restart the application
          pm2 restart marin-pest-control-backend || pm2 start ecosystem.config.js
          
          # Check if frontend needs building
          if [ -d "../frontend" ]; then
            cd ../frontend
            npm ci
            npm run build
          fi
          
          # Restart nginx
          sudo systemctl reload nginx
          
          echo "🚀 Deployment completed successfully!"
